### PR TITLE
Make rig_ui_template modular: allow individual rigs to add code.

### PR DESCRIPTION
**Pull request by angavrilov**
As mentioned in #1, current rigify has an extensibility problem because of the monolithic UI script template. That pull request implements an option to replace it with another script. However, I think that since the true issue here is the fact that it is monolithic, a better solution is to make it modular.

Currently individual rigs can only add code to one particular part of the UI script, namely the rig properties panel class. I implement a way to also add library imports, utility code, and class registration/deregistration entries, with simple but useful de-duplication functionality. As an example, super_limb rigs are converted to the new system, so the base template now only contains rig-independent code and generic utility functions.

### CODE REVIEW

**Comment by angavrilov** [comment]
Since with the template change rigs can return more data to the main rigify code, I decided to get rid of the IK_follow hack as well in favor of an explicit returned list.

**Comment by eigen-value** [comment]
Hi @angavrilov,
I'm reading this after I read your comments on PR [#1](https://github.com/eigen-value/rigify/pull/1).
I think modularity of the template is a good idea, and the way you implemented it saves back-compat which is my main concern.
I have some design doubts on the rig_type side though.
You're using a ui.py file where you save snippets both pertaining to UI and utility functions plus a "get_script_utilities()" method called by limbs only...
I know, the script file is called "rig_UI" so it'd make sense but thing is, we should make an effort to add a cleaner code since rigify is already pretty much hard to read.
I'd opted for a different kind of OO structure with limbs all inheriting from a base class and that base class being responsible of returning all the common methods and snippets.
I'd also keep the snippets inside the single limb class module or maybe use a resources file holding snippet strings only. I'd implement the get_script method as a method of the base class overriden by children classes

**Comment by angavrilov** [comment]
Well, about that ui.py thing, I put the stuff there simply because it already contains the create_script function used by all the limb rigs. I thought it would be logical if the utilities were in the same file as the panel scripts that use them.

Edit: Basically, in order to make evaluating this pull request easier, I tried to change as little as possible while still achieving the desired result.

**Comment by angavrilov** [comment]
Btw, it's not related to this per se, but while testing that all code works with these changes, I noticed a problem with the limbs: even when IK stretch is set all the way to 0, it doesn't actually truly disable scale. And one effect of scale is that repeatedly pressing the pole toggle function gradually changes the shape of the limb.

**Comment by eigen-value** [comment]
Hi @angavrilov,
My target is to get a better, more sound, readable and maintanable codebase.
We have code snippets strings, methods and utilities scattered all around, and this is bad.
So, if we find a bug that needs to be fixed (btw please post any bug you find in the 2.79 version of rigify, on the official bug tracker) then we try and fix it without questioning the design.
If, on the other hand, it's a new feature then we must have a design discussion together, before proceeding to implement it.
As I said, the template modularity is a good idea, but does it add to the complexity of developing custom rig_types? probaby... does it raise design questions about where to put methods and snippets? I think so. Specifically, does the limbs codebase need a cleanup? definitely!

**Comment by angavrilov** [comment]
Limbs here are just an example of using modularity, and it actually technically breaks backward compatibility with legacy limbs, because I imagine that they expect limb operators to be in the template by default, and it's only safe to modularize the non-legacy pole target switch option. I can just as easily refactor my finger code to use the new modular approach to serve as an example of the new API (in fact I plan to do it as soon as this goes in in some form). Therefore, I think that refactoring limbs is out of the scope of this pull request, and discussion should focus on the design of the core interface between rigs and generate.py.

Regarding design of the core modularity feature, the main thing to discuss here that I see is whether to return the template code from generate() or add a new method. A dedicated method may be a more 'clean' design, but generate() on the other hand changes the way things work less significantly and keeps all code together; and it makes it easier to change the set of utility code depending on what generate does, if the rig author so desires. Of course, if the new method is called after generate(), information transfer can also be achieved via class fields. Or maybe it's better if the templates depended only on the rig parameters... The 'script' and 'noparent_bones' definitely have to come from generate().

Modularity may add to the technical complexity of new rig types, but it reduces ugliness by allowing you to keep everything related to the rig in one place, and in my view is required if you really want to support independent user rig types.

It may be a good practice to keep all utility code strings exposed as global constants in some module, so that other rigs (even user defined ones) could potentially borrow them for code sharing purposes - seeing as deduplication of identical strings for code sharing is a documented part of the new modularity feature.

If you consider commit diff size, maybe it's even better to split the existing code in rig_ui_template into separate strings for use in the modularity feature, but keep it there.

**Comment by angavrilov** [comment]
So, since I kinda agree that that ui.py thing is messy, and there is no obvious better place to put that code in, I decided it's better to keep it in rig_ui_template.py for now in the interest of reducing the patch line count, and just split the code chunk into separate variables for rigs to import.

I also thought it's probably better to make a convention that all such variables should be lists for consistency (even if they only contain one string), and tried to come up with a sensible naming scheme.

Finally, since backward compatibility is a priority, I decided to include the operators that legacy rigs expect by default, although the new rigs still properly request them and let the deduplication feature do its job.

**Pull request closed without merging**
