### PR TITLE
External Rigs, metarigs and UI templates

### PR DESCRIPTION
**Pull request by PiOverFour**
Hi,
I finally got around to implementing external metarigs and ui templates loading.
I don't know if you've given thought to the issue on your end, but this PR would enable us to work with your official rigify version.
You can test this with our cutout rigs, located in our [external-rigs](https://github.com/LesFeesSpeciales/rigify/tree/external-rigs) branch right now, which will become the main branch for the cutout rigs, should you accept this PR.

As you will see, the directory structure for external rigs simply mirrors core rigify's one:
```
.
├── __init__.py
├── metarigs
│   ├── __init__.py
│   └── Subtype
│       ├── __init__.py
│       ├── metarig1.py
│       ├── metarig2.py
├── rigs
│   ├── __init__.py
│   └── subtype
│       ├── rig1.py
│       ├── rig2.py
└── ui_templates
    ├── template1.py
```

One issue I think may be problematic for your design is how I tackled the UI templates system. As I already mentioned, it is very important for us to be able to develop an alternative rig UI, and it shouldn't change much for users not using our cutout rigs.
When external rigs are loaded, a list appears in the Rigify Buttons panel, allowing to chose from multiple UI templates. Defaults are set when adding a metarig, but the choice needs to be exposed when creating a rig from scratch.

Also, right now the loading of metarigs and ui templates duplicates a lot of code in utils, metarig_menus and template_list. Perhaps it could be done more legibly and efficiently?

Anyway, feel free to contact me for any questions!

### CODE REVIEW

**Comment by eigen-value** [comment]
Hi @PiOverFour ,
I'm checking the commits and I have some concern on 55ff19f.
In __init__ you join 'rigs' subdir iff there's actually a 'rigs' subdir under the user-def custom folder. But then, everywhere else you simply join 'rigs' to every custom_rigs_folder or external_folder path variable.
I wonder what happens if there's no user-def 'rigs' subdir...

**Comment by eigen-value** [comment]
Sorry @PiOverFour, you probably did fix it in the following commits... maybe having this PR squashed in 2 commits would have been better.
I'll pull locally and test it

**Comment by PiOverFour** [comment]
Ah yes sorry, I did fix things along the way...

**Comment by PiOverFour** [comment]
Hi @eigen-value, have you had time to test this PR? Should I rebase it on your recent changes right now, or wait to get your approval? Are there things I should do in the meantime to make it more suitable for merge?  
Thanks.

**Comment by eigen-value** [comment]
Hi Damien,I'm relatively less busy these days so I will try to. I'm sure it won't take long since you tested it already I guess.Sorry for waiting so longInviato dal mio dispositivo Huawei-------- Messaggio originale --------Oggetto: Re: [eigen-value/rigify] External Rigs, metarigs and UI templates (#1)Da: PiOverFour A: eigen-value/rigify CC: Lucio Rossi ,Mention Hi @eigen-value, have you had time to test this PR? Should I rebase it on your recent changes right now, or wait to get your approval? Are there things I should do in the meantime to make it more suitable for merge?
Thanks.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/eigen-value/rigify","title":"eigen-value/rigify","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/eigen-value/rigify"}},"updates":{"snippets":[{"icon":"PERSON","message":"@PiOverFour in #1: Hi @eigen-value, have you had time to test this PR? Should I rebase it on your recent changes right now, or wait to get your approval? Are there things I should do in the meantime to make it more suitable for merge?  \r\nThanks."}],"action":{"name":"View Pull Request","url":"https://github.com/eigen-value/rigify/pull/1#issuecomment-384688958"}}}---Dona il 5 per mille all'Università Federico II per sostenere studenti e ricercatoriCodice Fiscale Università degli Studi di Napoli Federico II 00876220633

**Comment by eigen-value** [comment]
@PiOverFour I've been trying to merge this PR locally but with no luck...
First I tried on the current version resolving the conflicts and I have two errors:
- I cannot perform relative imports in the external folder so I get import exceptions as soon as I choose a new external directory
- I also get a "can't find 'external' key" in the rig_dict, but that's related to the first one I guess, since __init__ fails on loading modules

I thought it was a merging problem so I locally reset the head to the commit where you made the PR, pulled it, but the issue is still there...
Maybe it is better if you try and rebase the PR over the current mad_master branch

**Comment by PiOverFour** [comment]
I rebased and took the opportunity to squash the commits.  
I'm afraid I can't reproduce the error you got. Could it be related to the external rigs themselves, those you used for your test? Are they the updated ones in our [external-rigs branch](https://github.com/LesFeesSpeciales/rigify/tree/external-rigs)? This is the one I tested with, downloading it afresh from GH.

**Comment by eigen-value** [comment]
Hi @PiOverFour thank you for the update.
I tried your [external-rigs](https://github.com/LesFeesSpeciales/rigify/tree/external-rigs) and it works, though when I try with another folder I'm still having these exceptions... I'm baffled

here's the folder
[ext_rigs_2.zip](https://github.com/eigen-value/rigify/files/1963362/ext_rigs_2.zip)
it's pretty basic. In the rigs folder I put a neck_short Rig class trying to import a test function from another module (custom_utils). Blender gives me:

`SystemError: Parent module '' not loaded...`

on th the line:

`from .custom_utils import trial_fun`

I double checked your files and mine, they differ only in one thing: the **line separator**. Mine have CRLF yours LF only so I guess you're using a *nix system. I don't know if this can be the problem though.

Could you please give a try to my test folder?

**Comment by eigen-value** [comment]
@PiOverFour ok, no it's not the line separators.
I've tried modifing your folder a bit, I added two files in the rigs folder one is importing a function from another and I get the issue again.
Could you try and do the same?
Besides, I noticed many strange things happening switching from one external folder to another (eg pantins metarigs are not removed, Human metarig disappears and such...)
I think you should try other external folders to cover the general case

**Comment by PiOverFour** [comment]
After testing I understand the error: it may have not been the right decision, but I made the directory search for the rigs so that it expects two levels: inside `rigs`, there should be just the `__init__.py` and rig groups or directories, and inside each of those the rigs themselves. The idea behind this was that the user could manage their rigs more easily, just copying whole directories instead of individual files.
Maybe it should be able to handle either folders or files. I will try and see what I can do.

Thanks for the use case!

**Comment by PiOverFour** [comment]
Actually, the reason behind this choice wasn't exactly the one I said in my previous comment. It is more simply that it is the structure found in Rigify itself, with each rig having a sort of namespace. It felt more logical, then, to mirror this structure, both in files and in code.  
It seems that it was also designed that way when you first wrote the external import code? At least I get the exact same error with your commit `f76c449... fix: 'external' keyerror`, pointing the external rigs preference to the `rigify-external/rigs` dir instead of just `rigify-external`.

**Comment by eigen-value** [comment]
I most probably didn't consider this at first, but it's maybe better if we leave the possibility to relative import in the base folder as well... just in case someone wants to put utilities files there, same as in the official rigify folder.
do you feel like giving it a try?

**Comment by PiOverFour** [comment]
I agree, it would make more sense from a user's perspective. However I tried this last week and didn't get very far, with all the import magic going on in `utils.get_rig_type()`.
I will try and implement this, but it won't be very soon as we're rather busy at the moment...

**Comment by PiOverFour** [comment]
Hi Lucio, I believe I managed to implement this functionality, while cleaning various areas.
What I did was remove the relative mode entirely in rig_lists, which added complexity. Now every rig is imported in absolute mode, including the core rigify ones.
For this to work I had to add a `base_path` option, relative to which the import is done in `utils.get_type()`.

There may be some things which I haven't tested, but I couldn't find any bug.

Please tell me if you need me to squash the commits again, as I preferred to keep them separate for now.

**Comment by eigen-value** [comment]
Hi @PiOverFour 
Great! Looks like it's working real good...
A couple of little fixes are needed:

1. If I point to an empty folder (or one without the utils.py file with the folder constants defined in METARIG_DIR, RIG_DIR, TEMPLATE_DIR) I get an error on __init__.py line 177: The variable custom_metarigs_folder is accessed before assignement (IDE marks this as a warning as well).
I tried initializing both custom_metarigs_folder and custom_templates_folder to the empty string...
but I have the annoyng side-effect that the Human metarig disappears from the menu! And also it doesn't look like metarigs are unloaded...
See here an example where I first opened a 'Pantin' folder and then I point to an empty one
immagine

2. If you put an __init__.py file in the ui_templates subfolder it is enlisted in the templates option list. Though templates files are not modules, I think it's better skipping files starting with the underscore.

**Comment by PiOverFour** [comment]
Thank you for pointing these out! I believe your two points are now fixed, as well as a number of others:
* legacy mode was completely broken
* when a legacy rig or metarig existed in `bpy.data`, *Generate Rig* was replaced by the *Switch to Legacy* button, even if the active metarig was not legacy (this problem existed prior to this PR)

Sorry for not being more involved, we're almost at the end of a project and I don't have much time to code...

EDIT: Nevermind, point #1 is actually not fixed yet. Sorry about that.
EDIT 2: *Now* it is fixed! Whew!

**Comment by eigen-value** [comment]
Hi @PiOverFour 
Great! I'll look into it asap :)

**Comment by angavrilov** [comment]
On the topic of rig_ui_template.py, I don't understand why there is a single global script for that in the first place. Given how rigs are supposed to be modular, it makes much more sense if they e.g. had a method that returned the code they want added at the top of the script. There needs to be some way to avoid duplicates if multiple rigs want the same bit of code, but this way is a lot more flexible.

**Comment by eigen-value** [comment]
Hi @angavrilov 
Bear in mind that rigify has some legacy code which was difficult to get rid of without breaking back-compatibility, I'd really appreciate if you could give me your thoughts about the new_rig_base_classes branch where I'm trying to organize the code in a better way...
About the rig_ui_template, there is a method which is already returning extra snippets which go on top of the main script and it is the Rig class generate method itself (btw the idea of naming all the rig_type classes as Rig() is just awful)
The main script is for holding functions (eg snapping functions) that are needed for the final rig to work __independently__ from rigify itself, so you don't have to install rigify to use a rigify-generated rig.
The snippets returned by the generate method are used for exposing the specific rig_type props and drivers in the N panel.
I agree with the fact that a separate method would make more sense but that would mean modifying the main generate function as well (it can be done but it's a design issue and can potentially break compatibility with custom and legacy rig_types)
Together with @PiOverFour we're trying to overcome the limitation of a single rig_ui_template so one can choose its fav rig_ui_template before hitting generate

**Comment by PiOverFour** [comment]
Hi @eigen-value and @angavrilov,
some update on this issue. This is still WIP for bug fixing and maybe some more UI design, but the external feature sets mechanism basically works. With this new system:
* you can add several feature sets by choosing a .zip file on disk. This will get installed to a new `2.79/scripts/rigify` dir.
* You can then choose from these in the Pose Bone's Rigify Types panel, and in the Armature's Rigify Buttons panel in Edit Mode. This lets you only add rig types from this feature set.
* For now, there is no mechanism to filter Metarigs in the Add menu. I figured it wasn't as much important, since Metarigs needing Rigs from multiple feature sets need to access them anyway.
* Lucio, I remember you said it would be useful to be able to disable feature sets from the list in the user preferences. For now, I haven't implemented that, and I think it would be redundant with the selector in the Properties panels.

## Important modifications
* I entirely deleted the `rigify_collection` property from the `rig_lists` module, since it doesn't seem to be used anywhere, nor serve any purpose. If you know its use, I can put it back, but deleting it removed several tedious conditional tests, in `generate` in particular.
* I added a feature_sets file, since the new classes and functions weren't related to anything else. This can be moved to utils/... when it is split.
* External rigs used to be reloaded all the time, during generation, but also on each UI draw (`get_rig_type()` in `BONE_PT_rigify_buttons`'s `draw()`).  
The rig modules are now stored in the `rigs` dictionary in `rig_lists.py`. This dictionary replaces both the `rig_list` and `rig_dict`, which served the same purpose as far as I could tell.

## Note
* Legacy mode does not work yet. EDIT: It works now.

I'd appreciate if you guys could test and break it with your own external modules!

**Comment by angavrilov** [comment]
Why are you adding all individual feature sets to path? I sort of feel it may be polluting the namespace, and the feature set itself should be a module within the containing dir.

**Comment by PiOverFour** [comment]
@angavrilov You're right, it's indeed better that way.

**Comment by angavrilov** [comment]
Since you mentioned utils split, I wonder if you would have any comments on #7.

**Comment by PiOverFour** [comment]
Legacy mode is now fixed, the problem was that it relied on `rigify_collection`.

**Comment by PiOverFour** [comment]
Hi @eigen-value, has there been any update on @angavrilov's and my pull requests?

**Comment by eigen-value** [comment]
@PiOverFour 
I have some troules with this branch on a 2.79b fresh install.
I checked out the PR on a new branch but when I open UserPrefs and I click on Rigify External Features sets I get a console error.
immagine

**Comment by PiOverFour** [comment]
Sorry about that. I didn't check that the `rigify` dir existed in config before trying to list its contents...

**Comment by eigen-value** [comment]
@PiOverFour 
nope, the error is still there...
it has trouble with the invocation of the method: bpy.utils.script_path_user()
I guess the problem is os dependent since on both Win10 and Win7 the folder returned (.../User/AppData/Roaming/Blender Foundation/Blender/2.79/script) is not present

**Comment by PiOverFour** [comment]
I understand what was happening: I always install rigify in the user path, and thus never had this error because the script dir always existed. I tried replacing the Blender rigify install itself, and indeed I get the same error on any platform.

**Comment by PiOverFour** [comment]
Squashed commits from may.

**Comment by eigen-value** [comment]
Ok then, looks like it's done!
There's a caveat though. Merging #1 with #5 was causing conflicts on the rig_ui_templates management system. In order to keep both your commits and @angavrilov 's all ui_templates should provide the following snippets (albeit empty):
- UI_IMPORTS
- UI_UTILITIES
- UI_REGISTER
- UI_BASE_UTILITIES
- UI_SLIDERS
and the function:
- layers_ui()

**Comment by eigen-value** [comment]
@PiOverFour ,
The fix was not enough, I had the same exception raisgin for non-existent feature_sets_path
I did some fixes [here](https://github.com/eigen-value/rigify/commit/04353c7e972d326e89cdd16e179491fff50fdfff) then I tried the following:
- Copy/paste entire legacy folder on /Desktop/trial_sets/
- zipped the folder as trial_sets.zip
- Clicked install set from file in user preferences
And I have this:
immagine

What's wrong?

**Comment by eigen-value** [comment]
@PiOverFour 
I've tried with [pantins](https://github.com/LesFeesSpeciales/rigify/tree/external-rigs) and it's working, so it's probably just the relative imports in legacy making a mess

**Comment by angavrilov** [comment]
I'd not expect legacy rigs to work as external ones due to relative
imports. Maybe we can prepare an 'official' legacy package with correct
import paths or something; it could also work with the new modular ui
script API, removing the need for always emitting the IK operators that was
mentioned in chat.

**Comment by eigen-value** [comment]
Just a non-standard test I tried. I don't have other custom feature sets. As I said I tried pantins and it's installing, though the templates are not compatible with the modular structure

**Comment by PiOverFour** [comment]
There are at least to problems with your test:
* `__init__.py` should be empty
* There should be an intermediary directory in metarigs, like `metarigs/Legacy/human.py`

When doing these modifications, the rigs load up, and they are detected as legacy rigs.

I just finished modifying the Pantins to work with the modular templates, though with some modifications to generate.py I'll bring up later.

**Pull request closed without merging**
